#!/bin/zsh
[[ -n "${CU_MOCK_NATIVE_LOG:-}" ]] && print -r -- "$*" >> "$CU_MOCK_NATIVE_LOG"
mock_window_id="${CU_MOCK_WINDOW_ID:-42}"
case "${1:-}" in
  context)
    printf 'META\t%s\t4242\t100\t200\t800\t600\tDemo\tDemo Window\tcom.example.Demo\n' "$mock_window_id"
    print -r -- $'AX\tw0.0\tAXButton\tSave\t125\t235\t50\t30\tAXPress\t56'
    print -r -- $'AX\tw0.1\tAXButton\tSave\t225\t235\t60\t30\tAXPress\t'
    ;;
  bounds|activate)
    print -r -- "${mock_window_id}"$'\t4242\t100\t200\t800\t600\tDemo\tDemo Window'
    ;;
  ocr)
    if [[ "${CU_MOCK_OCR_MODE:-}" == display-only && "${3:-}" == 0 && "${4:-}" == 0 ]]; then
      print -r -- $'File\t50\t15\t25\t15\t0.990'
    else
      print -r -- $'Save\t150\t250\t50\t20\t0.990'
      print -r -- $'Cancel\t250\t250\t60\t20\t0.980'
    fi
    ;;
  windows)
    print -r -- "${mock_window_id}"$'\t4242\t100\t200\t800\t600\tDemo\tDemo Window'
    ;;
  display)
    print -r -- $'1\t0\t0\t1440\t900'
    ;;
  app-info)
    print -r -- $'4242\tDemo\tcom.example.Demo'
    ;;
  ax-status)
    print -r -- 'trusted'
    ;;
  ax-tree)
    [[ "${CU_MOCK_NATIVE_AX_UNAVAILABLE:-0}" == 1 ]] && exit 3
    print -r -- $'w0.0\tAXButton\tSave\t125\t235\t50\t30\tAXPress\t56'
    print -r -- $'w0.1\tAXButton\tSave\t225\t235\t60\t30\tAXPress\t'
    ;;
  ax-perform)
    print -r -- 'AXPress'
    ;;
  fingerprint)
    print -r -- "${CU_MOCK_FINGERPRINT:-abc123}"
    ;;
  paste)
    [[ -f "${2:-}" ]] || exit 65
    print -r -- 'pasted'
    ;;
  scroll)
    print -r -- 'scrolled'
    ;;
  *) exit 64 ;;
esac
